name: Build

on:
  push:
    branches: [ master ]
    tags:
    - 'v*'
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: make openvpn

    - name: Create distribution
      run: make dist-all

    - name: Upload artifact for linux amd64
      uses: actions/upload-artifact@v2
      with:
        name: openvpn-linux-amd64.tar.gz
        path: dist/openvpn-linux-amd64.tar.gz
    - name: Upload artifact for linux arm64
      uses: actions/upload-artifact@v2
      with:
        name: openvpn-linux-arm64.tar.gz
        path: dist/openvpn-linux-arm64.tar.gz

    - name: Upload artifact for windows
      uses: actions/upload-artifact@v2
      with:
        name: openvpn-windows-amd64.zip
        path: dist/openvpn-windows-amd64.zip

  release:
    name: Release
    runs-on: ubuntu-18.04
    needs: Build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}

    - name: Download artifacts for linux amd64
      uses: actions/download-artifact@v2
      with:
        name: openvpn-linux-amd64.tar.gz
        path: ./
    
    - name: Download artifacts for linux arm64
      uses: actions/download-artifact@v2
      with:
        name: openvpn-linux-arm64.tar.gz
        path: ./

    - name: Download artifacts for windows
      uses: actions/download-artifact@v2
      with:
        name: openvpn-windows-amd64.zip
        path: ./

    - name: debug
      run: ls -lR

    - name: Upload openvpn-linux-amd64.tar.gz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./openvpn-linux-amd64.tar.gz
        asset_name: openvpn-linux-amd64.tar.gz
        asset_content_type: application/gzip

    - name: Upload openvpn-linux-arm64.tar.gz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./openvpn-linux-arm64.tar.gz
        asset_name: openvpn-linux-arm64.tar.gz
        asset_content_type: application/gzip

    - name: Upload openvpn-windows-amd64.zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./openvpn-windows-amd64.zip
        asset_name: openvpn-windows-amd64.zip
        asset_content_type: application/zip
