on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Build

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build ./cmd/input-openvpn
      working-directory: openvpn

    - name: Create distribution
      run: tar cvzf openvpn-linux-amd64.tar.gz input-openvpn
      working-directory: openvpn

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: openvpn-linux-amd64.tar.gz
        path: openvpn/openvpn-linux-amd64.tar.gz
