name: Build

on:
  push:
    branches: [ master ]
    tags:
    - 'v*'
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build ./cmd/input-openvpn
      working-directory: openvpn

    - name: Create distribution
      run: tar cvzf openvpn-linux-amd64.tar.gz input-openvpn
      working-directory: openvpn

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: openvpn-linux-amd64.tar.gz
        path: openvpn/openvpn-linux-amd64.tar.gz

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/v')
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: openvpn/openvpn-linux-amd64.tar.gz
        asset_name: openvpn-linux-amd64.tar.gz.zip
        asset_content_type: application/zip
